---
boot_drive: nvme0n1p2

wg_interface: trojsten
wg_peers:
  - public_key: "bA8kI2T0JF7J6w7W7Th3Y8Jv126M5CJX1FwpOGT+KDc="
    endpoint: "158.195.86.170:8484"
    allowed_ips: "172.16.0.0/16"
    persistent_keepalive: 25
